name: Create CV in PDF format

on:
  push:
    paths:
      - "cv.md" # Triggers the workflow only when cv.md is modified

jobs:
  convert:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt install \
            pandoc \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-extra-utils \
            texlive-latex-extra \
            texlive-xetex \
            fonts-ubuntu

      - name: Update Font Cache
        run: sudo fc-cache -fv

      - name: Convert Markdown to PDF
        run: pandoc cv.md -o cv.pdf --pdf-engine=xelatex

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: true
          CUSTOM_BUMP_MESSAGE: "MAJOR"
          CUSTOM_MAJOR_WORDS: "MAJOR"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.bump_version.outputs.new_tag }}
          name: CV ${{ steps.bump_version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: tanyagray/action-upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv.pdf
          asset_name: cv-boris-khasanov.pdf
          asset_content_type: application/pdf
