name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'cv.md' # Triggers the workflow only when cv.md is modified

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-xetex  # Install LaTeX packages needed for PDF generation

      - name: Convert Markdown to PDF
        run: pandoc cv.md -o cv.pdf

      - name: Commit and Push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cv.pdf
          git commit -m "Update cv.pdf" || echo "No changes to commit"
          git push
