name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'cv.md'  # Triggers the workflow for changes to Markdown files in any directory

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y texlive-xetex  # Install LaTeX packages needed for PDF generation

      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdf  # Ensures the pdf directory exists
          for file in *.md; do
            pandoc "$file" -o "pdf/${file%.md}.pdf"
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdf/
